### ISSUE TITLE
areContainedPublishable is not updating

### ISSUE THREAD

**Issue by amberwebb** [Connexions/cnx-authoring#181]
Steps to reproduce:
1. Create book
2. Create page 1
3. Create page 2 and add a role
4. Click workspace
5. Click book that was just created
6. areContainedPublishable is true in JSON. It should be false since page 2 has a pending role.
7. Add a role to the first page - now areContainedPublishable is false

**Comment by karenc** [comment]
The comment for areContainedPublishable in the code says "flag to say whether any contained models are publishable".  So areContainedPublishable is true for the book because page 1 is publishable.

If it's supposed to be true only if *all* the contained models are publishable, I can change the code.  
@reedstrm what do you think?

**Comment by pumazi** [comment]
The value of this flag is questionable, now that we have included the ``isPublishable`` state in the contents tree. However, the results as seen are correct. If one or more of the contained documents are publishable (that excludes the binder itself), the value will be ``True``.
