### ISSUE TITLE
Derived Copy - images disappear

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-authoring#205]
On dev.cnx.org, when a Page is derived, the images are no longer visible. All of the GET on /resources are returning a 404.

See original at https://github.com/Connexions/webview/issues/915

**Comment by rich-hart** [comment]
This seems to be an issue with the current instance of cnx-authoring running on dev.cnx.org. When a page is being derived, the image resource hash string is being changed when it is sent to the editor. For example the image http://dev.cnx.org/resources/db2be0305f84bc13c2e3ff04639b8270 in the original page is being changed to http://dev.cnx.org/resources/68651684a49cebfde8ffc3f76a33a8184cdfdc63 in the derived page, the hash strings should be the same. This seems to only be a bug in dev at the moment because I've tested it on my own local instance and beta and the image rendered without any problems. I didn't try it on legacybeta but I will soon.

**Comment by rich-hart** [comment]
@reedstrm " downloading both images, i can confirm that they are the same.  Archive is using md5sum so the url is http://dev.cnx.org/resources/db2be0305f84bc13c2e3ff04639b8270 and authoring is using sha1sum so the url is http://dev.cnx.org:8900/resources/68651684a49cebfde8ffc3f76a33a8184cdfdc63 " - karen

**Comment by rich-hart** [comment]
What I don't understand is why using two different hash algorithms hasn't caused a problem in the past.

**Comment by karenc** [comment]
We're supposed to be using sha1 on both.  We added a sha1 column in the archive files table: https://github.com/Connexions/cnx-upgrade/commit/910b81b8533433068b478e3ee44f917e4c4e2e80.

We're match against md5 and sha1 in the sql for resources: https://github.com/Connexions/cnx-archive/blob/f14429059b493facfa2ab6a1275ac8402ca3e021/cnxarchive/sql/get-resource.sql

**Comment by rich-hart** [comment]
Both links are working now
http://dev.cnx.org/resources/db2be0305f84bc13c2e3ff04639b8270

http://dev.cnx.org/resources/68651684a49cebfde8ffc3f76a33a8184cdfdc63
